package pl.pistolrange.pistolrange_server.domain;

public enum WeaponLawCategory {
    WSZYSTKIE(),
    USTAWA_O_BRONI_I_AMUNICJI(),
    PRZECHOWYWANIE_I_NOSZENIE_BRONI,
    PRZEWOZENIE_BRONI_SRODKAMI_TRANSPORTU_PUBLICZNEGO,
    BEZPIECZENSTWO_NA_STRZELNICACH,
    SANKCJE_KARNE,
    OBRONA_KONIECZNA_I_STAN_WYZSZEJ_KONIECZNOSCI;
}
